import './globals.css'
import type { Metadata } from 'next'
import { Sidebar } from '../components/modules/Sidebar/Sidebar'
import { Header } from '../components/modules/Header/Header'
import { CallTypeProvider } from '@/context/CallTypeContext'


export const metadata: Metadata = {
    title: 'Skilla Test',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <html lang="ru">
            <CallTypeProvider>
                <body>
                    <Header/>
                    <Sidebar/>
                    {children}</body>
            </CallTypeProvider>
        </html>
    )
}
